"use client";
import React from 'react';
import Footer from '../components/global/Footer';

const TermsAndConditions = () => {
  return (
    <>
        <div className="min-h-[80vh] bg-gray-900 text-gray-300" style={{ paddingTop: '100px' }}>
        <div className="container mx-auto px-4 pt-8">
            <h1 className="text-4xl font-bold mb-6 text-white">Terms and Conditions</h1>
            <p className="text-lg mb-4">
            Welcome to Holiday Havens, your AI-powered travel companion. By using our services, you agree to the following terms and conditions. Please read them carefully.
            </p>

            <h2 className="text-2xl font-semibold mb-4 text-orange-400">1. Use of Our Service</h2>
            <p className="mb-4">
            Our platform offers travel booking assistance through AI technology. By using our service, you acknowledge that the recommendations are generated by AI and are provided for informational purposes only. You are responsible for verifying all travel details before making a booking.
            </p>

            <h2 className="text-2xl font-semibold mb-4 text-orange-400">2. User Responsibilities</h2>
            <p className="mb-4">
            You agree to provide accurate information when using our services. Any false or misleading information may result in the termination of your account and access to our platform.
            </p>

            <h2 className="text-2xl font-semibold mb-4 text-orange-400">3. Payments and Refunds</h2>
            <p className="mb-4">
            All payments made through our platform are subject to the terms and conditions of the respective third-party providers. We do not process payments directly and cannot provide refunds. You must contact the third-party provider for any payment-related issues.
            </p>

            <h2 className="text-2xl font-semibold mb-4 text-orange-400">4. Cancellation Policy</h2>
            <p className="mb-4">
            Cancellation policies for bookings depend on the terms set by the individual service providers (hotels, airlines, etc.). Please refer to the provider’s terms when booking. We are not responsible for cancellations or refunds.
            </p>

            <h2 className="text-2xl font-semibold mb-4 text-orange-400">5. Intellectual Property</h2>
            <p className="mb-4">
            All content, including but not limited to text, images, and software, on this website is the intellectual property of Holiday Havens and is protected by copyright laws. You may not copy, distribute, or modify any content without prior written consent.
            </p>

            <h2 className="text-2xl font-semibold mb-4 text-orange-400">6. Changes to Terms</h2>
            <p className="mb-4">
            We reserve the right to modify these terms and conditions at any time. Your continued use of our services after any changes constitutes acceptance of the new terms.
            </p>

            <p className="text-lg mt-6">
            If you have any questions regarding these terms, please contact us at <a href="mailto:support@holidayhavens.com" className="text-orange-400">support@holidayhavens.com</a>.
            </p>
        </div>
        
        </div>
    <Footer />
    </>
  );
};

export default TermsAndConditions;
